### ISSUE TITLE
App stops working 

### ISSUE THREAD

**Issue by aks9130** [Mahmud0808/ColorBlendr#100]
In one ui 6 the app suddenly stopped working picking colours and the basic adaptive theming according to wallpaper colours

**Comment by Mahmud0808** [comment]
Can you try v1.2 and check if that works?

**Comment by Mano5JP** [comment]
1.5 version is not compatible with OneUI 6.1. But tried 1.2 and it is functional.

**Comment by aks9130** [comment]
1.2 worked thanks
