### ISSUE TITLE
Stuck in permissions screen

### ISSUE THREAD

**Issue by Nyasper46** [Mahmud0808/ColorBlendr#106]
The app literally stuck in the permission screen even I have Shizuku running, I tried all like reinstall etc but...
![Screenshot_20240716_205504](https://github.com/user-attachments/assets/82fe168b-af6e-403e-ba84-77b29585e630)
![Screenshot_20240716_205623](https://github.com/user-attachments/assets/65a56159-0fce-47d9-b341-babaa754e9f7)

**Comment by Mahmud0808** [comment]
Did you grant notification and storage permission?

**Comment by Nyasper46** [comment]
> Did you grant notification and storage permission?

Yep, all permissions granted and authorized in Shizuku

**Comment by Mahmud0808** [comment]
Provide a screen recording with logs

**Comment by Nyasper46** [comment]
How I can get the logs?

**Comment by Nyasper46** [comment]
Well I recorded it with ScreenCam and Logfox in my vivo Y36 Android 14, I hope this helps
[17_07-00-00-09_738.log](https://github.com/user-attachments/files/16257130/17_07-00-00-09_738.log)

https://github.com/user-attachments/assets/74766ee3-5d19-45ba-b28b-1d0dd5e7688a

**Comment by Mahmud0808** [comment]
If I remember correctly, there should be one more permission to grant in that list but it's not showing for you. Can you try landscape mode or change your dpi/font size to default? The texts are huge and it's probably cutting off that permission card.

**Comment by Nyasper46** [comment]
Okay was that, thank you so much, but I reccomend you do a scroll bar or something. I have big text because my eyes are shit

**Comment by Mahmud0808** [comment]
I will take that in my consideration. Thank you.
