### ISSUE TITLE
Gboard no longer themes

### ISSUE THREAD

**Issue by androidacy-user** [Mahmud0808/ColorBlendr#109]
Hello! 

After a recent Gboard update, only the accent color is applied to gboard. No other colors apply, and it can't be selected under per app themes (it later unselected itself)

**Comment by Mahmud0808** [comment]
Known, although the background lightness slider still affects gboard colors, so there's still hope. I will check later when I get enough time.

**Comment by Mahmud0808** [comment]
![Screenshot_2024-08-14-19-42-00-811_tk zwander fabricateoverlay](https://github.com/user-attachments/assets/172df3bd-de73-4047-bdc4-8fc607573a2d)

Unfortunately gboard resources are now obfuscated.

**Comment by Mahmud0808** [comment]
Use Rboard theme manager.
