### ISSUE TITLE
Pitch Black Theme option causes some elements to become colored rather than darker

### ISSUE THREAD

**Issue by PsychoPhysicist** [Mahmud0808/ColorBlendr#124]
Most noticeable on Gboard and search within Settings
![Screenshot_20240907-142337](https://github.com/user-attachments/assets/baa50cec-e6cd-4c7a-97fe-0b46606f7f7b)
![Screenshot_20240907-142408](https://github.com/user-attachments/assets/43a1b97c-2c21-476a-b11a-3f67245186b3)

Version 1.7
Android 14 AP2A.240605.024
Magisk 27
Pixel 7 Pro

**Comment by Mahmud0808** [comment]
For me both turns pitch black (not the latest gboard though, that's obfuscated now)

**Comment by PsychoPhysicist** [comment]
Why would it do anything to Gboard then?  Also, it's only search, the rest of Settings works correctly.  I also have Iconify installed, if that makes a difference.

**Comment by Mahmud0808** [comment]
I am using CrDroid 10.8 and settings search screen becomes pure black here

**Comment by PsychoPhysicist** [comment]
Tried "Force per app theme" on both Settings (com.android.settings) and
Settings Services (com.google.android.settings.intellegence).  No change to
either, even after force stopping them both, restarting SystemUI and
finally rebooting.
                     -Michael Biernat

**Comment by Mahmud0808** [comment]
Try manual color overrides. Find out which color corresponds to that settings search page color. Take a screenshot of both the color palette and search page color. I'll look into it.
