### ISSUE TITLE
Background color picker

### ISSUE THREAD

**Issue by allday5850** [Mahmud0808/ColorBlendr#126]
All I want/have wanted for awhile now is just a simple background color chooser. That and only that.  Entirely independent. No reliance on Material You or any other factors besides the color that I have specifically chosen. I just want to be able to choose my background and my accent colors independently. And when I change one indont want the other to change with it. 
I know this isn't a fair comparison, but like in substratum you can pick exact background and accent and they have no bearing on one another. Is this possible?

**Comment by Mahmud0808** [comment]
Use root method, shizuku is limited.
