### ISSUE TITLE
ADB support?

### ISSUE THREAD

**Issue by milindgoel15** [Mahmud0808/ColorBlendr#129]
If possible, can you add ADB support as well? So we can grant permissions using arb rather than using shizuku?

**Comment by hanubeki** [comment]
It is how Repainter (the competing app) works without root.

**Comment by Mahmud0808** [comment]
> It is how Repainter (the competing app) works without root.

Repainter isn't a competing app. ColorBlendr is FOSS and just works, so a comparison isn't fair. Repainter works in three different ways:

1. If the ROM has the Repainter service integrated, it can change colors without requiring root through that service. Ofcourse no OEM integrated that service, it's just custom ROMs.
2. It has built-in Shizuku within the Repainter app itself.
3. It works with root/superuser permissions.

I'm not sure if Repainter supports ADB, but I don't intend to integrate Shizuku within the app, if that's what you meant.

**Comment by hanubeki** [comment]
Shizuku in Repainter is an older method, currently it uses built-in wireless adb library to grant `android.permission.WRITE_SECURE_SETTINGS` IIRC.

**Comment by AltyFox** [comment]
https://github.com/DanTheMan827/OnDeviceADB/
@Mahmud0808 
Here's an open source on device ADB service.

Even has functions for auto detecting the port when configuring wireless ADB where the user only needs to enter the code

**Comment by hanubeki** [comment]
This is a C# library so I'm not sure if this can be used in Java/Kotlin projects.

**Comment by Mahmud0808** [comment]
I will look into this [LADB](https://github.com/tytydraco/LADB) and [aShellYou](https://github.com/DP-Hridayan/aShellYou), seems promising

**Comment by AltyFox** [comment]
> This is a C# library so I'm not sure if this can be used in Java/Kotlin projects.

Correct, however it could still be implemented. It literally just uses a binary of ADB compiled for Android architectures, and can be executed as such. And since it's the actual Google ADB binary, it'll behave as expected

Upon further inspection, it looks like LADB does the same thing

**Comment by hanubeki** [comment]
> I will look into this [LADB](https://github.com/tytydraco/LADB) and [aShellYou](https://github.com/DP-Hridayan/aShellYou), seems promising

aShellYou uses Shizuku to run shell commands so I think it is not for this feature request.

**Comment by Mahmud0808** [comment]
> > I will look into this [LADB](https://github.com/tytydraco/LADB) and [aShellYou](https://github.com/DP-Hridayan/aShellYou), seems promising
> 
> aShellYou uses Shizuku to run shell commands so I think it is not for this feature request.

It now has wireless debugging too. I checked and also talked with the developer.

**Comment by AltyFox** [comment]
As long as we have generic tcpip 5555 as well.  Since that survives being disconnected from wifi

**Comment by Mahmud0808** [comment]
The worst part is, F-Droid will now reject the next update just because of the ADB binaries.
