### ISSUE TITLE
Outdated Wallpaper colours

### ISSUE THREAD

**Issue by PhilippKosarev** [Mahmud0808/ColorBlendr#130]
Context: My previous wallpaper was green, now it's orange.
For some reason ColorBlendr picks the colours from the old wallpaper.
![Screenshot_20240929_014343_ColorBlendr](https://github.com/user-attachments/assets/44ef72ab-9bbc-4801-8543-edee89a404ce)

**Comment by Mahmud0808** [comment]
How come it applied orange but showing green?

**Comment by PhilippKosarev** [comment]
I applied the colour palette through my phone's settings which is why the app had orange colours. Changing the wallpaper while ColorBlendr was active fixed the issue.
Does ColorBlendr pick up the new wallpaper only when it's active?

**Comment by Mahmud0808** [comment]
Yes ColorBlendr needs to be active, so disable battery optimization for the app. Also it should extract wallpaper colors on every app launch.
