### ISSUE TITLE
Unclear color palette

### ISSUE THREAD

**Issue by AndraxDev** [Mahmud0808/ColorBlendr#133]
It is not clear which row in the color paletter is responsible for which accent type. Proposed solution: Add A1, A2, A3, N1 and N2 labels so user can understand which color he edits. You can add labels here (marked red)

![Screenshot_20241011-001013.png](https://github.com/user-attachments/assets/753758c4-2ea1-4a2b-ac3f-49d283500722)

**Comment by Mahmud0808** [comment]
I didn't think it was that necessary as most people don't care about palette names at all.
