### ISSUE TITLE
"Blank Permission is not granted"

### ISSUE THREAD

**Issue by SKYY999** [Mahmud0808/ColorBlendr#134]
After enabling all of the permissions, I can't continue with either "Root" or "Shizuku" for no apparent reason. All it does is display a notification that says: "Blank Permission is not granted".

What do i do??

**Comment by Mahmud0808** [comment]
Can you provide screenshot or something

**Comment by lalala-png** [comment]
Hi! I'm having the exact same problem sadly

**Comment by lalala-png** [comment]
https://github.com/user-attachments/assets/3c5e3bb2-0400-47bf-9ff7-acad358c1265

here! hope it works

**Comment by Mahmud0808** [comment]
> here! hope it works btw I'm on xiaomi redmi note 13

Have you granted shizuku or root permission to ColorBlendr?

**Comment by lalala-png** [comment]
ah I'm sorry I'm bad at this, how do I do that?

**Comment by Mahmud0808** [comment]
> ah I'm sorry I'm bad at this, how do I do that?

You can find videos on YouTube about how to use shizuku.
