### ISSUE TITLE
Pixel launcher search box color not affected on Android 15 QPR1 Beta 3

### ISSUE THREAD

**Issue by TikkaMasala1** [Mahmud0808/ColorBlendr#146]
![Screenshot_20241029-200819](https://github.com/user-attachments/assets/88021c05-a3bf-40eb-8f9a-6549f766bad3)

Only happening in QPR1 B3
The widget indicates the color set in colorblendr

**Comment by Mahmud0808** [comment]
Did you select pixel launcher in per app theme list?

**Comment by TikkaMasala1** [comment]
> Did you select pixel launcher in per app theme list?

That worked on the icons, but the search box at the bottom is not changing (despite also selecting com.google.android.googlequicksearchbox in the per app list.)
![Screenshot_20241101-141237](https://github.com/user-attachments/assets/0bc12f63-8666-4f5b-bf47-233748be817c)

**Comment by Mahmud0808** [comment]
I currently don't have a way to test it, so it might take some time. However, I did test it on the non-beta version of Android 15, and it worked fine there.
