### ISSUE TITLE
Remove DependencyInfoBlock for F-Droid

### ISSUE THREAD

**Issue by linsui** [Mahmud0808/ColorBlendr#156]
We find that there is a `DependencyInfoBlock` in your APK.

It's a [Signing block](https://bi-zone.medium.com/easter-egg-in-apk-files-what-is-frosting-f356aa9f4d1) added by AGP and encrypted with the Google public key so it can't be read by anyone else except Google. You can read more about it [here](https://gitlab.com/fdroid/admin/-/issues/367) and [here](https://gitlab.com/fdroid/fdroidserver/-/issues/1056).

While this was added a while ago, we were only enforcing it for new apps, and recently we started scanning updates too.

Could you please disable it with the following code?

```
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

Thanks!

**Comment by Mahmud0808** [comment]
Do I need to release another update with the changes to get it listed on Fdroid?

Another question, how do I remove some screenshots from Fdroid? I have removed it from fastlane directory but these are still visible on Fdroid.

**Comment by linsui** [comment]
A new version is good. :)

https://gitlab.com/fdroid/admin/-/issues/377 The files need to be removed manually.
