### ISSUE TITLE
Inclusion to F-Droid

### ISSUE THREAD

**Issue by ClockGen** [Mahmud0808/ColorBlendr#18]
Hello, I'd like to propose to include your app into F-Droid. Somebody opened a request for packaging on F-Droid gitlab (https://gitlab.com/fdroid/rfp/-/issues/2626) so I need your permission to proceed.

**Comment by ClockGen** [comment]
I actually didn't check who filed the RFP, so I assume that was you (https://gitlab.com/DrDisagree). Anyway, in this case, it's still worth keeping this issue open if any problems arise.

**Comment by Mahmud0808** [comment]
> I actually didn't check who filed the RFP, so I assume that was you (https://gitlab.com/DrDisagree). Anyway, in this case, it's still worth keeping this issue open if any problems arise.

Yeah that was me. :))

**Comment by ClockGen** [comment]
Merge request for ColorBlendr in fdroiddata repo: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14345

**Comment by ClockGen** [comment]
To set up reproducible builds, please always upload apk built from the same git tag, right now it seems the latest apk in release is built using latest commit, not the release tag: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14345#note_1726468398. Another thing, please name the apk without the version name, something like "app-release.apk", so F-Droid system could pick it up.

**Comment by Mahmud0808** [comment]
> To set up reproducible builds, please always upload apk built from the same git tag, right now it seems the latest apk in release is built using latest commit, not the release tag: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14345#note_1726468398. Another thing, please name the apk without the version name, something like "app-release.apk", so F-Droid system could pick it up.

Noted. Will do the necessary changes.

**Comment by ClockGen** [comment]
Ideally it'd be good if you tag a new release.

**Comment by Mahmud0808** [comment]
> To set up reproducible builds, please always upload apk built from the same git tag

Could you clarify a bit more? Shall I use same tag each time from here?
![image](https://github.com/Mahmud0808/ColorBlendr/assets/29881338/286c9c88-a324-4bd5-a0a5-0d9703ea18c0)

> Also, ideally it'd be good if you tag a new release.

Did you mean I need to release another build now? Can I merge the translations from crowdin before doing that?

**Comment by ClockGen** [comment]
> > To set up reproducible builds, please always upload apk built from the same git tag
> 
> Could you clarify a bit more? Shall I use same tag each time from here?

No, I meant that you should tag a new release and attach an apk built from the same tag, right now verification failed because it seems that the attached apk is built with newer commits not present at the release tag. 

I also just noticed that versionName and tags are not aligned, unfortunately with current apk versionName it's not possible for F-Droid to pick it up with each version. 

F-Droid can use github release links and substitute parts of it with versionName (%v) and versionCode (%c), so for example when building repo tagged with v1.0b7, we can use the link:
`https://github.com/Mahmud0808/ColorBlendr/releases/download/%v/ColorBlendr.%v.apk`  
but as you can see, with current:
`https://github.com/Mahmud0808/ColorBlendr/releases/download/v1.0b7/ColorBlendr.1.0.beta.7.apk`  
it's not possible because versionName doesn't match (since current versionName is `1.0 beta 7`, it will try to substitute %v with that and fail, because there's no such link).  

Please make future tag names. versionName in apk filename and versionName in app/build.gradle.kts match (so for git tag `v1.0b8` versionName would also be `v1.0b8`, attached apk name would be `ColorBlendr.v1.0b8.apk` and so on).

> Did you mean I need to release another build now? Can I merge the translations from crowdin before doing that?

Of course, there's no rush.

**Comment by Mahmud0808** [comment]
https://github.com/Mahmud0808/ColorBlendr/releases/tag/v1.0b8

Is this correct now? Let me know. Thank you for all the guiding :)

**Comment by ClockGen** [comment]
Yes, everything seems to be in order, I'm gonna run a local build to see if everything is ok.

**Comment by ClockGen** [comment]
The app has been merged https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14345
It'll (hopefully) be available in the next f-droid server run or two.

**Comment by Mahmud0808** [comment]
Thank you.

**Comment by Mahmud0808** [comment]
@ClockGen are [these](https://github.com/Mahmud0808/ColorBlendr/commit/7010be75580db35a1aef57d27855cf743f7d5685) libs allowed to be included? These libs are for xposed framework and required to build an xposed module. Xposed framework API is under Apache 2.0 license according to [this](https://mvnrepository.com/artifact/de.robv.android.xposed/api/82).

**Comment by ClockGen** [comment]
Jars or other precompiles are not allowed in general, apache 2 is fine however you either have to find these libraries in allowed maven repos (https://gitlab.com/fdroid/fdroidserver/-/blob/master/fdroidserver/scanner.py?ref_type=heads#L452, Google() and MavenCentral() are also allowed) or add their source code and compile together with the rest of the app.

**Comment by Mahmud0808** [comment]
```Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find de.robv.android.xposed:api:82.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/de/robv/android/xposed/api/82/api-82.pom
  - https://repo.maven.apache.org/maven2/de/robv/android/xposed/api/82/api-82.pom
  - https://jitpack.io/de/robv/android/xposed/api/82/api-82.pom
Required by:
    project :app
```

 All of them are currently dead and only available option is the libs. I talked about it for my other repo [here](https://gitlab.com/fdroid/rfp/-/issues/2559) before.

**Comment by ClockGen** [comment]
Unfortunately it seems the only way left is to compile the libs too during the app's build (although I don't know if it's even possible nowadays since it only depended on jcenter https://github.com/rovo89/XposedBridge/blob/art/build.gradle which was shut down).

**Comment by ClockGen** [comment]
ColorBlendr is now available in F-Droid.
