### ISSUE TITLE
App tries to theme itself

### ISSUE THREAD

**Issue by androidacy-user** [Mahmud0808/ColorBlendr#20]
As stated above, ColorBlendr keeps getting selected by itself under per app theme.

This leads to a potential crash loop on colors applying as the app keeps getting refreshed by the system.

**Comment by Mahmud0808** [comment]
Are you using beta 7? It has been commented out.

https://github.com/Mahmud0808/ColorBlendr/blob/master/app/src/main/java/com/drdisagree/colorblendr/utils/FabricatedUtil.java#L127
