### ISSUE TITLE
Lock Screen Clock Not Affected

### ISSUE THREAD

**Issue by RGBok** [Mahmud0808/ColorBlendr#21]
The lock screen clock on AOSP 14 continues to follow the default color scheme (any clock that is not the one that's also on AOSP 13). Is it possible to make it also follow the color scheme.

**Comment by Mahmud0808** [comment]
Search for "com.android.systemui.clocks" and select all from "Force per app theme" list.

**Comment by RGBok** [comment]
> Search for "com.android.systemui.clocks" and select all from "Force per app theme" list.

Thanks for the response. I tried that first before opening this issue and nothing changed, when I went back to check if they were selected, they were unselected again. I restarted system UI, and when that didn't work also tried restarting the whole device.

**Comment by Mahmud0808** [comment]
It seems that adjusting the clock color will require implementation through the Xposed Framework.

**Comment by RGBok** [comment]
Wow. I guess they really locked down on it this time around. Interesting though that the default clock keeps the new color scheme but any of the new ones do not.
