### ISSUE TITLE
Pitch black and HyperOS

### ISSUE THREAD

**Issue by RoyaleOne** [Mahmud0808/ColorBlendr#27]
Pitch black mode seems to get reset after every reboot and system ui reboot and i have to turn pitch black off and on for it to work, if this could be fixed it would be amazing

Android: 14
HyperOS: 1.0.3.0 from xiaomi.eu
Device: Poco x5 pro

**Comment by Mahmud0808** [comment]
Working fine here. Using same rom, same device. Make sure to enable Background autostart for ColorBlendr and select No restrictions in Battery saver.

![photo_2024-01-21_16-08-59](https://github.com/Mahmud0808/ColorBlendr/assets/29881338/d1b55860-804c-4f17-a506-91176c0712e5)

**Comment by RoyaleOne** [comment]
Yeah it just fixed itself after a few reboots, thanks for helping tho
