### ISSUE TITLE
supported help。

### ISSUE THREAD

**Issue by Tobapuww** [Mahmud0808/ColorBlendr#3]
ColorBlendr in the tank Android12.1 API 32 but android 12L also API 32 Is it supported?

If Android 12L is supported, this program does not work for my device.

![593aaae0fd4961c1d7459f3d20bcc63](https://github.com/Mahmud0808/ColorBlendr/assets/139964294/28c9680f-a1d3-44b4-a83e-10286185fa05)
![0493f2c55aa78c52f6eb153de7f21e8](https://github.com/Mahmud0808/ColorBlendr/assets/139964294/6e1ebb0e-0682-4694-a3a3-acf9c4e7abbb)
![bb835529fd905b87db90076edaa2f38](https://github.com/Mahmud0808/ColorBlendr/assets/139964294/1eff60e8-3779-4b39-93ba-72139abaa234)

I am currently using the 1.0.0 beta3 dev version built with developer source code and support for Chinese Simplified. No other code has been changed.

**Comment by Mahmud0808** [comment]
12.1 and 12L is same. If it's not working on your device, provide LSPosed log + SystemUI.apk of your rom

**Comment by Tobapuww** [comment]
I have submitted the required documents for the developer to review, please feel free to contact me if necessary.

[LSPosed_2023-12-14T20_04_23.036.zip](https://github.com/Mahmud0808/ColorBlendr/files/13673059/LSPosed_2023-12-14T20_04_23.036.zip)

[SystemUI.zip](https://github.com/Mahmud0808/ColorBlendr/files/13673089/SystemUI.zip)

**Comment by Mahmud0808** [comment]
There is no issue in your logs. After enabling ColorBlendr, make sure to restart SystemUI or reboot your phone.

**Comment by Mahmud0808** [comment]
Try latest version, if issue still persists, let me know.

**Comment by Tobapuww** [comment]
After the update to the Beta6 version, all functions and options will function normally.
