### ISSUE TITLE
Make intents able to change theme

### ISSUE THREAD

**Issue by helloyanis** [Mahmud0808/ColorBlendr#31]
Here's what I want to do, I'd like to have a theme that changes throuought the day. I've already got automation apps that can send an intent at any given time. But I don't know if you can send an intent to ColorblendR with extra theme data to change the theme.
Or maybe there's a better way to do it?

**Comment by Mahmud0808** [comment]
Tell me the process (what you are using to send intent and how), I can then do something about it.

**Comment by helloyanis** [comment]
I'm using [this application](https://f-droid.org/packages/com.jens.automation2/) that allows you to send data to other apps through multiple methods and to add intents via the menu "Open another program" in the actions menu when editing a new routine. But since there is afaik no way to send an intent to get your theme changed, I can't send anything yet (besides opening the app)

Thanks for the help!

**Comment by helloyanis** [comment]
I'm using [this application](https://f-droid.org/packages/com.jens.automation2/) that allows you to send data to other apps through multiple methods and to add intents via the menu "Open another program" in the actions menu when editing a new routine. But since there is afaik no way to send an intent to get your theme changed, I can't send anything yet (besides opening the app)

Thanks for the help!

**Comment by Mahmud0808** [comment]
I will look into it. What kind of data are you willing to send? Maybe color code? Which can be used to generate and apply a pallete.

**Comment by helloyanis** [comment]
I was thinking maybe the path to a backup file, so it can apply the colors and the style you want seamlessly, not limited to having to pick just a color
Let's say you want to switch from color A in vibrant style to color B in rainbow style, passing just  a color won't allow you to change that.

But it's a good start if this gets implemented first

**Comment by Mahmud0808** [comment]
Tried the app you mentioned on android 14 but it doesn't seem to send any broadcast even if I run it manually. I don't know what I am doing wrong.

**Comment by helloyanis** [comment]
Here's what I got from my testing, I don't know if it broadcasts an event but it can open the app just fine. I'm also running Android 14.

https://github.com/Mahmud0808/ColorBlendr/assets/40769776/12ff3bcc-3fd9-4fee-81f9-b332bebca455

You might also need to add a [broadcast receiver](https://stackoverflow.com/a/33611355) to your app so that it can receive the broadcast.

If the app *sending* the broadcast is at fault, then I don't know how to test it out, I'd need an app that logs broadcasts sent to it (so we can see if it works or not) but I'm not aware of any of them.

**Comment by Mahmud0808** [comment]
ColorBlendr already has intent receivers. Lemme know if you can make sure that broadcast sending actually works in that app.

**Comment by russianspy1234** [comment]
Can you provide the intent receiver? I have Tasker and would like to  be able to use it to poke this app to update it's colors whicih currently doesn't seem to be working when my wallpaper changes.

**Comment by Mahmud0808** [comment]
> Are the dials / graph in the app in the main colors section or te styles section supposed to change too? Cuz it doesn't look like they do.

Everything changes according to wallpaper color if you are not using any custom color.

**Comment by russianspy1234** [comment]
> > Are the dials / graph in the app in the main colors section or te styles section supposed to change too? Cuz it doesn't look like they do.
> 
> Everything changes according to wallpaper color if you are not using any custom color.
> 
> Also make sure colorblendr isn't getting killed from background. Then you don't need tasker for this either.

Yeah I just like to poke my apps to update sometimes and not rely on services / active notifications.

**Comment by e-t-l** [comment]
This could also help with #108. I would like to use completely different color pallettes based on whether the device Dark Theme is active. This could be accomplished within ColorBlendr, and/or it could be achieved manually by the user sending an intent to load a different color config file

**Comment by Mahmud0808** [comment]
> This could also help with #108. I would like to use completely different color pallettes based on whether the device Dark Theme is active. This could be accomplished within ColorBlendr, and/or it could be achieved manually by the user sending an intent to load a different color config file

I still can't think of something that's efficient. Implementing the UI for time based config selection will be very complex for me.
