### ISSUE TITLE
Add One UI 6 support

### ISSUE THREAD

**Issue by alvinchitena** [Mahmud0808/ColorBlendr#39]
The switch from One UI 5 to 6 on Samsung devices seems to have broken the ability (of many similar apps) to change the primary material you color. Is this something that can be fixed? Just asking, no expectations.

**Comment by Mahmud0808** [comment]
ColorBlendr is working on oneui 6 as far as I know. But I can't test as I don't have Samsung device.

**Comment by Xisrr1** [comment]
Working fine for me. Though it takes long to update to the wallpaper color
