### ISSUE TITLE
Per app theme issues

### ISSUE THREAD

**Issue by androidacy-user** [Mahmud0808/ColorBlendr#41]
A couple of issues with per app themes:

With forced:
1) Backgrounds are messed up in most apps (i.e., black where there should be a different variant, several variants having the same color, backgrounds changed to make app hard to use [Google app, app manager, various other md3 apps])
2) Text seems to be forced white [Google messages]

Without:
1) Some apps [Google Messages, Google] do not seem to respect any background color changes

**Comment by Mahmud0808** [comment]
Provide screenshots

**Comment by Mahmud0808** [comment]
Also some apps you mentioned (Messages, Google), these can't be themed. Google obfuscated the resources of these apps and it's almost impossible for anyone to theme.

**Comment by Mahmud0808** [comment]
I know how it works. It pulls one specific color and then creates its own color palette. So no, I don't have full control like the other apps where I can change each individual color.
