### ISSUE TITLE
Procedure stuck at the third screen

### ISSUE THREAD

**Issue by CavaleriOmar** [Mahmud0808/ColorBlendr#43]
Xiaomi 12X
Miui 14.0.4, Android 13

Despite having set no power saving and automatic startup, the wizard procedure stops at the third screen

I have Shizuku active, and pressing "Start," nothing happens (lowering the notification curtain and closing it right away prompts for root as per the message in the screenshot)

![Screenshot_2024-02-13-19-17-08-957_com.drdisagree.colorblendr.jpg](https://github.com/Mahmud0808/ColorBlendr/assets/54171779/1ad5d427-5211-4b3e-9319-ed92666793ae)

For the moment I am using Repainter, but besides being out of date for a long time, I prefer to use as few apps on the playstore as possible

**Comment by Mahmud0808** [comment]
You are using old version which doesn't support shizuku

**Comment by CavaleriOmar** [comment]
> You are using old version which doesn't support shizuku

On F-Droid, support for Shizuku is specified, but I now see that the app is 2 versions behind

**Comment by Mahmud0808** [comment]
Yeah F-Droid isn't picking up new builds. I need to contact with them.
