### ISSUE TITLE
Primary / secondary / tertiary color picker

### ISSUE THREAD

**Issue by Anachrion** [Mahmud0808/ColorBlendr#45]
Hello ! 
I just discovered this application, great work, really. I'm amazed by the results achieved. 
I was wondering if it was possible to add a third option / tab in the first sceen. There is already 'Wallpaper colors' and 'Basic colors'. What about allowing the user to pick the primary, secondary and tertiary colors all by himself ? I didn't checked the code and I'm not an android developper, but naively I suppose the whole palette is processed from these 3 picks right ? 
Best regards and thanks again for this wonderful app.

**Comment by Anachrion** [comment]
I'm rooted (Lineage 21 + Magisk 27.0). How can I achieve this ?

**Comment by Mahmud0808** [comment]
I haven't implemented it yet. Will check when I have some free time.

**Comment by alkeryn** [comment]
any news on this ? :)

**Comment by Mahmud0808** [comment]
> any news on this ? :)

Done :)
