### ISSUE TITLE
Icon Shape changes after applying ColorBlendr with Shizuku

### ISSUE THREAD

**Issue by JoeJoeTV** [Mahmud0808/ColorBlendr#46]
### Description

When using ColorBlendr with Shizuku, the system icon shape gets changed and can sometimes not be changed back until ColorBlendr is disabled again and the device is rebooted. Changing the Icon shape using the System "Moto" app also doesn't help.

### Specs

**Device:** Motorola moto g73
**Android Version:** 13
**ColorBlendr Version:** 1.2
**Using Shizuku:** Yes

**Comment by Mahmud0808** [comment]
Fixed in ab30fc6d6045fb2bb8fd97c12ff2b22971c7c2fb hopefully.
