### ISSUE TITLE
Can't use rom customizations

### ISSUE THREAD

**Issue by Extremelycolorful** [Mahmud0808/ColorBlendr#47]
Hello dear developer

there have some bugs after apply the app's them i can't change my fonts and icon shape in Motorola phone. The system is myui 4.0

**Comment by Extremelycolorful** [comment]
> there have some bugs after apply the app's them i can't change my fonts and icon shape in Motorola phone. The system is myui 4.0

btw the problem is exist after i inactive the app theme

**Comment by Mahmud0808** [comment]
It has been fixed here https://github.com/Mahmud0808/ColorBlendr/commit/ab30fc6d6045fb2bb8fd97c12ff2b22971c7c2fb and will be available in future version. For now, disable colorblendr theming service, then reboot device to get those customizations back.

**Comment by Extremelycolorful** [comment]
Thanks your reply，i will to try🥰🥰🥰
