### ISSUE TITLE
[Bug] Can't use the black theme when the target app's MaterialComponents version is v1.11+

### ISSUE THREAD

**Issue by Jesse205** [Mahmud0808/ColorBlendr#5]
- System: MIUI 14, Android 13
- MaterialComponents version: 1.11.0

[Surface with elevation overlay has been replaced with tonal surface colors in Material's components.](https://github.com/material-components/material-components-android/blob/master/docs/theming/Color.md#using-surface-with-elevation-overlay)

Many of the dark natural colors in the latest material components v1.11 are based on N2 600 color. However, the black background of the xposed module is achieved by modifying 900 colors, which can cause this bug.

![image](https://github.com/Mahmud0808/ColorBlendr/assets/51242302/82b89fde-abd1-4948-a70b-0b67cffc453d)
![image](https://github.com/Mahmud0808/ColorBlendr/assets/51242302/23442d3b-9c47-46a2-97bc-134c29544d9e)

I don't know much about framework, but I think the module should implement a modification of `android:lStar` for effect

## Related issues

- https://github.com/F0x1d/LogFox/issues/88

**Comment by Mahmud0808** [comment]
I have seen it and already thought of a fix (internal testing worked), though it will take a few days or week to finish my work, You can track progress here https://github.com/Mahmud0808/ColorBlendr/compare/master...root_service

Thanks for the detailed report btw.
