### ISSUE TITLE
Does this app works with live wallpaper?

### ISSUE THREAD

**Issue by KawaiiZapic** [Mahmud0808/ColorBlendr#50]
It seems this app is not working with live wallpaper, after live wallpaper set, app will pick color from system default wallpaper and never follow live wallpaper update.   
I'm on Android 13, MIUI 14, Muzei is my live wallpaper app, I use Muzei switch wallpaper automatic everyday.  It seems Repainter works with live wallpaper so it's possible should be possible to pick color from live wallpaper instead of system default wallpaper.

**Comment by Mahmud0808** [comment]
It is possible to extract colors from live wallpaper, I just don't know how yet. And so haven't implemented it.
