### ISSUE TITLE
Colors not applying

### ISSUE THREAD

**Issue by mizu-048** [Mahmud0808/ColorBlendr#52]
i used Repainter before this and that worked fine but this one actually reset the MaterialYou colors and is not doing anything.

Yes, i tried restarting the phone, the service is running and repainter is disabled.

Mode: Shizuku
OS: Android 12
Phone: Sparx neo 7
Version: v1.2

**Comment by Mahmud0808** [comment]
If Repainter is working for you, then there is no reason to use ColorBlendr :) Rootless method implementation is way better in repainter

**Comment by mizu-048** [comment]
but i prefer FOSS apps and repainter also requires google play for license verification, which is not possible on degoogled devices. So if colorBlendr were to work, it would be great.

Still a great addition to the foss apps though, nice work!

**Comment by Mahmud0808** [comment]
Android 12 rootless customization in ColorBlendr is very limited. You can only change seed color. Is that not working? Provide logs so that I can look into it.

**Comment by Mahmud0808** [comment]
Use any app like [LogFox](https://github.com/F0x1d/LogFox) and change options from ColorBlendr while that logger app is running.

**Comment by mizu-048** [comment]
so i'm back with some logs.
i forgot to tell you but the app crashes when I change the seed color in quick sucessions. So i've also included a crash log if thats of any significance
[14_03-14-35-22_838.zip](https://github.com/Mahmud0808/ColorBlendr/files/14600240/14_03-14-35-22_838.zip)
[crash-com-drdisagree-colorblendr-14_03-14-34-00_044.zip](https://github.com/Mahmud0808/ColorBlendr/files/14600241/crash-com-drdisagree-colorblendr-14_03-14-34-00_044.zip)

**Comment by Mahmud0808** [comment]
Looks like the app crash occurred in native code, harder to find exact cause.
Also don't see anything related in the logs you provided.

Can you maybe try this and check if it works for you? Don't forget to extract first.
[ColorBlendr v1.2.zip](https://github.com/Mahmud0808/ColorBlendr/files/14601410/ColorBlendr.v1.2.zip)

**Comment by mizu-048** [comment]
The apk you provided works, Nice! 
What did you change?

**Comment by Mahmud0808** [comment]
> What did you change?

Didn't change anything, it's built with the latest source that's already available in this repo. I just didn't get time to push a new update with the latest source code.
