### ISSUE TITLE
Jittery qs panel pulldown animation 

### ISSUE THREAD

**Issue by fabianlawrence** [Mahmud0808/ColorBlendr#57]
While pulling down notification/qs panel it is very jittery. Even more jitter if there is music player showing in qs panel.
Tried rebooting
Device - pixel 7 pro
Android 14 March update

**Comment by Mahmud0808** [comment]
Rooted or rootless? Provide logs.

**Comment by fabianlawrence** [comment]
It's rooted. Im using it along with pixel xpert with the light theme for qs panel. Sorry I don't know how to get the logs for the application.

**Comment by Mahmud0808** [comment]
Use LogFox app. Reproduce your issue and share logs.

**Comment by fabianlawrence** [comment]
I hope these are helpful.
[Uploading colorblendr log qs panel.log…]()

**Comment by Mahmud0808** [comment]
Can you disable other mods and confirm if it's still jittery?

**Comment by fabianlawrence** [comment]
It seems like pixel xpert was the problem. I disabled it and the jitter is gone. Thank you for the assistance.
