### ISSUE TITLE
pitch black mode does not work everywhere

### ISSUE THREAD

**Issue by realies** [Mahmud0808/ColorBlendr#58]
part of the notifications ui and the search view in the settings app are still light gray after enabling pitch black mode; husky-ota-ap1a.240305.019.a1-f1130be5 rooted

**Comment by Mahmud0808** [comment]
Provide screenshots, and I think the March OTA update broke it.

**Comment by realies** [comment]
the notifications background got black after setting background lightness to 0, but settings search for example is not affected:![](https://github.com/Mahmud0808/ColorBlendr/assets/5107843/e00fa575-9789-4883-8283-faf30433285d)

**Comment by Mahmud0808** [comment]
Can you show the homepage of colorblendr?

**Comment by realies** [comment]
![](https://github.com/Mahmud0808/ColorBlendr/assets/5107843/720b2482-e2f1-4f89-95d2-d41b70a3c5ba)

**Comment by realies** [comment]
> Enable "Override colors manually", then tap on `800` of 4th row and set it to black. That should do the trick.

It did; great design, thanks.

**Comment by Snuupy** [comment]
same issue, March patch, notifications aren't pitch black. Do you need my screenshots as well?
