### ISSUE TITLE
Palette colors 0 and 1000

### ISSUE THREAD

**Issue by Ruslik31** [Mahmud0808/ColorBlendr#60]
I hope you'll add the ability to change the colors of this palette. Because that's not possible at the moment 

Have a nice day

**Comment by Mahmud0808** [comment]
0 should be pure white and 100 should be pure black. It's used by various apps in various places. Changing it might ruin user interface. May I ask why are you trying to change it?

**Comment by Mahmud0808** [comment]
> In Iconify, this can be changed, just like in other similar ones. But unfortunately, their changes do not work correctly on the A14

Can you provide some examples (preferably screenshot) of changes not working correctly on A14?

**Comment by Ruslik31** [comment]
![Screenshot_20240328-141922_Iconify](https://github.com/Mahmud0808/ColorBlendr/assets/57251484/a003553a-7fa6-4d36-814b-ae2bd6d107b6)
![Screenshot_20240328-141933_Kotatsu](https://github.com/Mahmud0808/ColorBlendr/assets/57251484/e9d21e3c-602b-4a39-a4cf-5dcd7184aa23)

Of course, the theme is in-app in Iconify, it works partially in the system. But in applications that use new versions of materialcomponents, it does not work 

Only your app saves the situation.

**Comment by Ruslik31** [comment]
Screenshots from Iconify, and apps with dynamic theme

**Comment by Mahmud0808** [comment]
Ok I will look into it in my free time.

**Comment by Ruslik31** [comment]
Thank you, should I close the issue, or will you close it yourself?

**Comment by Mahmud0808** [comment]
> Thank you, should I close the issue, or will you close it yourself?

I'll close when I add the feature you requested.

**Comment by Ruslik31** [comment]
Ok, have a nice day

**Comment by Ruslik31** [comment]
I just noticed this issue change. 

It works for me 
![Screenshot_20240620-221458_crDroid Home](https://github.com/Mahmud0808/ColorBlendr/assets/57251484/33b69611-c86b-4c0a-b64e-de1f05935e53)

The colors of the text change in the system, and this is color 0

**Comment by Ruslik31** [comment]
Importing also restores these colors
