### ISSUE TITLE
I feel like I'm misunderstanding either this app or material you in general

### ISSUE THREAD

**Issue by russianspy1234** [Mahmud0808/ColorBlendr#61]
The colors picked don't seem to come from the wallpaper.  They change when the wallpaper changes, but like, random colors are included.
Here is an example wallpaper:
![u9rkbhc8ofpc1](https://github.com/Mahmud0808/ColorBlendr/assets/19349282/b15a42ab-937c-4515-8077-84879d5c4fd7)

And here is what the app pulled:
![Screenshot_20240320-144805](https://github.com/Mahmud0808/ColorBlendr/assets/19349282/23aad1f6-824e-4699-8d4e-15103af9af28)

Where did the blue come from? It seems like every time the wallpaper changes, I can go into the app and one of the options will be accurate, but it's not always the same one.  I'm trying to get it so that the most prominent color in my wallpaper is the  accent color / what colors my quick setting toggles.

**Comment by Mahmud0808** [comment]
![Screenshot_2024-03-29-19-53-09-429_com drdisagree colorblendr](https://github.com/Mahmud0808/ColorBlendr/assets/29881338/40089f55-94c7-4539-96da-68614be7b250)

For me it's picking only one color from the wallpaper you just gave, and that's correct behavior. In your case, ColorBlendr is probably getting killed from background, so it can't detect that you have changed your wallpaper. Try changing wallpaper while the app is running. Also make sure to enable auto start and disable battery optimization of the app.

**Comment by russianspy1234** [comment]
> ![Screenshot_2024-03-29-19-53-09-429_com drdisagree colorblendr](https://github.com/Mahmud0808/ColorBlendr/assets/29881338/40089f55-94c7-4539-96da-68614be7b250)
> 
> For me it's picking only one color from the wallpaper you just gave, and that's correct behavior. In your case, ColorBlendr is probably getting killed from background, so it can't detect that you have changed your wallpaper. Try changing wallpaper while the app is running. Also make sure to enable auto start and disable battery optimization of the app.

Hmm. The service is definitely running, I even left the notification enabled. My wallpaper gets changed on a schedule by an app, this one: https://play.google.com/store/apps/details?id=com.bryanwalsh.redditwallpaper2
Could that cause issues?

**Comment by Mahmud0808** [comment]
That shouldn't cause any issue if ColorBlendr is actually running in background.

**Comment by russianspy1234** [comment]
> That shouldn't cause any issue if ColorBlendr is actually running in background.

I can tell that it is because the pitch black theme is working

**Comment by russianspy1234** [comment]
> That shouldn't cause any issue if ColorBlendr is actually running in background.

I can tell that it is because the pitch black theme is working

**Comment by russianspy1234** [comment]
OK so I'm still trying to figure it out.  I think it might be related to the wallpaper changing while the screen is off.  I turned off all battery optimizations for this app, but it seems it still does not update if my wallpaper changer app changes it while the screen is off.
