### ISSUE TITLE
Does anyone have a restoration file of the default setup?

### ISSUE THREAD

**Issue by Platypus35** [Mahmud0808/ColorBlendr#63]
Hi, I was playing around with ColourBlendr, but now some of my colours look weird. For example, I want the default light pink theme back now, but no matter how much I tweak it, some colours appear as strange dark purples, which I do not want. I am using it through Shizuku. I should have backed up my default config before but was wondering if anyone could send me the default material you file which I could restore through the app. Thanks.
(Edit:grammar)
![Screenshot_20240331-192225](https://github.com/Mahmud0808/ColorBlendr/assets/131005836/55403f7d-0b2e-441b-bcad-46d04affb704)

**Comment by Mahmud0808** [comment]
Just disable ColorBlendr theming service from its settings, then reboot device. You should get original colors back.

**Comment by Ruslik31** [comment]
![Screenshot_20240331-233011_ColorBlendr](https://github.com/Mahmud0808/ColorBlendr/assets/57251484/706e77ea-1bfd-489c-b5cb-fbabb20f4a73)

You may have changed the brightness/accent saturation/background saturation

Maybe that's why you have such dark colors

**Comment by Platypus35** [comment]
> Just disable ColorBlendr theming service from its settings, then reboot device. You should get original colors back.

I tried disabling and restarting but the colours are still the same - e.g. my notification colour and certain other UI elements - e.g. the save button on photos editor is stuck on white colour as supposed to the pink it used to be, while the parts of the pin entering screen and calculator are stuck in strange dark purple colours.

**Comment by Mahmud0808** [comment]
Did you use per app theming section? Unselect all apps that are selected and then check.

**Comment by Platypus35** [comment]
> Did you use per app theming section? Unselect all apps that are selected and then check if it's fixed.

No, I am not rooted, just using shizuku so that isn't an option for me. I have completely disabled, uninstalled, and restarted, but the parts of the UI are stained white for some reason ![Screenshot_20240331-225544.png](https://github.com/Mahmud0808/ColorBlendr/assets/131005836/66af5d68-bfa4-44f7-93fb-fea19a9e14ca)

![Screenshot_20240331-225140.png](https://github.com/Mahmud0808/ColorBlendr/assets/131005836/430b0b60-6f6f-4a0f-a053-dd12dbef13f0)

**Comment by Mahmud0808** [comment]
If you are using shizuku then customizations are very limited and I don't think the issue you are having is because of ColorBlendr. Cause in shizuku mode, ColorBlendr just changes parameters given by the rom by default, it doesn't create or add anything new.

**Comment by Platypus35** [comment]
> If you are using shizuku then customizations are very limited and I don't think the issue you are having is because of ColorBlendr. Cause in shizuku mode, ColorBlendr just changes parameters given by the rom by default, it doesn't create or add anything new.

Huh strange, colourblendr is the only thing that I've played around with recently but I'll keep searching to find what's causing it. Any idea what else it could be or how to reset material you stuff without factory resetting?

**Comment by Mahmud0808** [comment]
> how to reset material you stuff without factory resetting?

Try changing wallpaper or change color from styles and wallpaper settings.

**Comment by Platypus35** [comment]
> > how to reset material you stuff without factory resetting?
> 
> Try changing wallpaper or change color from styles and wallpaper settings.

Tried everything now, even contacted Google support and the women didn't even know what material you was lmao. Anyways thanks for all your help and I guess there are bigger problems in the world than a slightly off UI colour.

**Comment by Platypus35** [comment]
@Mahmud0808 Hiya, sorry to bother you again, but after some asking Reddit, they say changes made by adb (with shizuku) can stay after apps have been uninstalled, so was wondering if you could send me a default config file for me to restore.

Admittedly it could be another app called Repainter causing the fuss, but thought this was worth one last shot before I'll just factory reset.

**Comment by Mahmud0808** [comment]
ColorBlendr already restores the default config when you disable the theming service from settings.

**Comment by Ruslik31** [comment]
Have you tried changing the theme with standard themes? They usually undo all the changes made by the apps
Settings - Wallpapers & Styles
