### ISSUE TITLE
Pitch black theme option greyed out

### ISSUE THREAD

**Issue by NaveeenGanesh** [Mahmud0808/ColorBlendr#64]
The pitch black theme option and the per app theme option are both not enabled for me. Please help me out with that. Thank you.
![Screenshot_20240406-045222_ColorBlendr](https://github.com/Mahmud0808/ColorBlendr/assets/44173838/9f7f7370-7d2f-4d51-8ae3-181a98ea79da)
![Screenshot_20240406-045449_ColorBlendr](https://github.com/Mahmud0808/ColorBlendr/assets/44173838/6061bb1e-ee30-4660-94e7-612dbb95af2e)

**Comment by Mahmud0808** [comment]
Rootless theming is very limited. You need root access for using the greyed out options.
