### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [Mahmud0808/ColorBlendr#75]
The recently added MaxPermSize is not supported on Java 17. Did you also downgrade the Java?

**Comment by Mahmud0808** [comment]
No I didn't downgrade java, I can remove MaxPermSize, what should I do next as I already pushed a build? Or do I have to release another one?

**Comment by linsui** [comment]
You can remove it in the next version. :)

**Comment by Mahmud0808** [comment]
Will fdroid show v1.4 though?

**Comment by linsui** [comment]
I'll remove MaxPermSize with sed.

**Comment by HiFIi** [comment]
OOPS :D this is 100% my fault

**Comment by licaon-kter** [comment]
sone in https://gitlab.com/fdroid/fdroiddata/-/commit/97bac66434853267fe158209f418c10046431c64, thanks

**Comment by licaon-kter** [comment]
reopen, https://gitlab.com/fdroid/fdroiddata/-/jobs/7589241110

you've tagged https://github.com/Mahmud0808/ColorBlendr/releases/tag/v1.6 to https://github.com/Mahmud0808/ColorBlendr/commit/4adb1a49ad0a411136914d715ddbf39da023beca

but the APK was built from 8c072d81a10478905bcbeef7ae8970216ebe198c ?

**Comment by Mahmud0808** [comment]
> you've tagged https://github.com/Mahmud0808/ColorBlendr/releases/tag/v1.6 to [4adb1a4](https://github.com/Mahmud0808/ColorBlendr/commit/4adb1a49ad0a411136914d715ddbf39da023beca)
> 
> but the APK was built from [8c072d8](https://github.com/Mahmud0808/ColorBlendr/commit/8c072d81a10478905bcbeef7ae8970216ebe198c) ?

I totally forgot about it, what should I do to fix it?

**Comment by licaon-kter** [comment]
Build from the commit used for the Tag, right?

That old commit does not even have the right versionCode/Name

**Comment by Mahmud0808** [comment]
You are right, incorrect commit tagged.

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/jobs/7606521092 1.7 is also built from a different commit.

**Comment by Mahmud0808** [comment]
https://gitlab.com/fdroid/fdroiddata/-/jobs/7883658510 did I do any mistake this time?

**Comment by licaon-kter** [comment]
The checkupdate job batches multiple apps to build, if you scroll at the actual build error you see some other app failed: https://gitlab.com/fdroid/fdroiddata/-/jobs/7883658510#L3085

**Comment by Mahmud0808** [comment]
> The checkupdate job batches multiple apps to build, if you scroll at the actual build error you see some other app failed: https://gitlab.com/fdroid/fdroiddata/-/jobs/7883658510#L3085

Ah ok got it
