### ISSUE TITLE
include or link to Shizuku tutorial

### ISSUE THREAD

**Issue by sosasees** [Mahmud0808/ColorBlendr#78]
i wanted to setup the app without root but now i can't find the instructions i need when [searching for "colorblendr setup shozuku"](https://duckduckgo.com/?q=colorblendr+setup+shizuku) — or at least not yet.
please include or link to the instructions if selected Shizuku during setup.

**Comment by Mahmud0808** [comment]
Do you know how to use shizuku?

**Comment by sosasees** [comment]
no.
i found ColorBlendr when browsing FDroid
and ColorBlendr setup is the first time in my life i have seen the name Shizuku.

**Comment by Mahmud0808** [comment]
Here's a straight forward tutorial https://www.youtube.com/watch?v=JAoUdRpfD3s

**Comment by sosasees** [comment]
thank you very much.
i just found ColorBlendr does not work on Samsung Android 12 at all without using root.

i got ColorBlendr because i hoped it would automatically adjust the colors with the [daily wallpaper](https://play.google.com/store/apps/details?id=com.google.android.apps.wallpaper) because Samsung Android 12 doesn't do it by default.

i might try this again if i get another Android distro that also doesn't change colors with daily wallpaper.

**Comment by sosasees** [comment]
both ColorBlendr versions don't work: ``1.2`` and ``1.3``
but it was worth a try.

now i know the actual issue thst needs solving:
ColorBlendr does not need to include a full tutorial for Shizuku, just a download link, because everything that comes after installing Shizuku is explained in the app Shizuku itself.
