### ISSUE TITLE
Allow choosing color range

### ISSUE THREAD

**Issue by Turhvjbufv** [Mahmud0808/ColorBlendr#8]
Sorry for the long read. 

My wallpaper have a lot of different colors in them, and color blender chooses the dominant color, please add an option so that color blender will choose a material color based on a range.
Example: let's say I set the range from purple to green(which also means that blue ext is included), and my current wallpaper has the colors yellow, red and blue, blue is the least dominant tho so usually it would choose yellow, but because I set the range from purple to green and red and yellow aren't in there, it chooses blue as the material color

**Comment by Mahmud0808** [comment]
You could just set a custom primary color instead. Wouldn't that solve your issue?

**Comment by Turhvjbufv** [comment]
That's only one color isn't it?
~~correct me if I'm wrong~~

**Comment by Mahmud0808** [comment]
> That's only one color isn't it?

Yeah correct, this way you can avoid colors you don't want.

**Comment by Turhvjbufv** [comment]
> > That's only one color isn't it?
> 
> Yeah correct, this way you can avoid colors you don't want.

- Indeed, but if I want to color blender to pick from a variety of colors(and avoid others), it wouldn't do that, it would only choose that primary color(and avoid all the other ones)

**Comment by Mahmud0808** [comment]
I get what you are asking for and it's very easy to implement acceptable hue range. But in my opinion most people wouldn

**Comment by Turhvjbufv** [comment]
> I get what you are asking for and it's very easy to implement acceptable hue range. But in my opinion most people wouldn't even understand hue range slider. But I will try to do something about it.

Thanks.
Maybe, the first time you press on it it will open a popup window that explains what it does, kinda like xposed menu in iconify

**Comment by Mahmud0808** [comment]
Unfortunately, I can't find a range slider that supports a gradient background to display the full spectrum of 360 hue colors. A few that I found are very old and doesn't work anymore.
