### ISSUE TITLE
Wallpaper change not being detected - Colors and color choices not changing

### ISSUE THREAD

**Issue by searinminecraft** [Mahmud0808/ColorBlendr#81]
When I change my wallpaper it does not change the colors. The app will think its the same and still give the same colors choices as if the wallpaper was the same.

The background service notification is there indicating its running in the background. I have not messed with any settings and the only use for this app is to force apps to use my system colors (that don't follow my system colors)

Android version: 12 (SQ3A.220705.004) unofficial LineageOS 19.1
ColorBlendr: 1.4 (12)

If you need any additional info just let me know

**Comment by Mahmud0808** [comment]
Keep ColorBlendr running (don't close from recents) and change wallpaper, see if that triggers it. And also make sure you are not using custom colors instead of wallpaper colors.

**Comment by searinminecraft** [comment]
> Keep ColorBlendr running (don't close from recents) and change wallpaper, see if that triggers it

Yes. Doing that triggers color changing. Its kinda annoying it does not change even if app is closed (even though background service is running)

**Comment by Mahmud0808** [comment]
Disable all battery optimization for ColorBlendr. Enable auto start of app. And check logs to be sure that your rom/kernel/whatever isn't killing the app from background.

**Comment by searinminecraft** [comment]
> Disable all battery optimization for ColorBlendr.

Doing that seems to fix the issue! I'm gonna be closing this issue for now unless I find more issues.

The app should prompt the user to disable battery optimizations on setup though
