### ISSUE TITLE
the color becomes strange

### ISSUE THREAD

**Issue by ammlr** [Mahmud0808/ColorBlendr#83]
After using this application on my hyper os, the color of the buttons becomes strange, color inversion and other oddities even occur. Even though I deleted the application and removed root, nothing changed. help

https://github.com/Mahmud0808/ColorBlendr/assets/30746607/bfcbbe9e-873e-4558-94b5-ea5f13a32a0b

**Comment by Mahmud0808** [comment]
Don't select all 3rd party apps. `Per app theming` is meant for material you supported apps. Like some of the google apps which has material 3 color support but still has different background color than rest of the apps. And to fix your issue, just simply disable ColorBlendr service from its settings before uninstalling.

**Comment by Mahmud0808** [comment]
Reboot your phone and apply different color from settings or change wallpaper to trigger new color generation.

**Comment by Mahmud0808** [comment]
I am also using it on HyperOS for months and till now no issue for me.
