### ISSUE TITLE
OneUI 6.1 broke support 

### ISSUE THREAD

**Issue by marciozomb13** [Mahmud0808/ColorBlendr#84]
After the OneUI update, app is completely broken, not a single feature work anymore (Shizuku mode) . I can help you to debug the app if you wish.

**Comment by Mahmud0808** [comment]
What OneUI update? And try the ColorBlendr v1.2

**Comment by marciozomb13** [comment]
OneUI 6.1, Android 14, released 2 days ago, using Colorblendr 1.4. I'll try 1.2.

**Comment by marciozomb13** [comment]
I can confirm version 1.2 works with OneUI 6.1. Thank you. Hope you can figure out what is wrong with 1.4 in this specific case.
