### ISSUE TITLE
After uninstallation, can't find basic color theme selection options in regular Settings app

### ISSUE THREAD

**Issue by Sophira** [Mahmud0808/ColorBlendr#85]
Hello,

I wanted to try out ColorBlendr for a bit, so I installed it from F-Droid on my Pixel 7.

After installing it (and using the rooting option), I found that I didn't want it after all, so I uninstalled it. (I did check to see if there was a particular method of uninstallation or "restore defaults" option that I should use, but couldn't find anything, so figured that maybe uninstalling might take care of that anyway.)

However, now, when I go to the "Wallpaper and style" page in Settings, I find that I'm missing the option for picking colour themes:

![After installing, exploring, then uninstalling, ColorBlendr](https://github.com/Mahmud0808/ColorBlendr/assets/1545217/ba444874-4b05-4a8b-8dd2-1e1648f64367)

I'm pretty sure I remember there being an option to pick between basic colour themes before, but I can't see it now. The option still exists when using other (non-Owner) profiles which existed before ColorBlendr was installed, though:

![Using a non-Owner profile, the theme settings are still there](https://github.com/Mahmud0808/ColorBlendr/assets/1545217/80d59858-2782-4ca8-b8ed-a96ca1a624c6)

If this isn't an issue with ColorBlendr, my apologies. If that's the case, does anybody know what the issue is?

In the case that this is something that installing ColorBlendr changed, how can I restore the option? (I'm happy with using `adb shell` and root if needed.)

Thank you!

**Comment by Sophira** [comment]
I should have mentioned the version, sorry! I had installed (and uninstalled) ColorBlendr v1.4.

**Comment by Mahmud0808** [comment]
Install ColorBlendr again, disable theming service from its settings. Then simply uninstall (and reboot if required).

**Comment by Sophira** [comment]
Thank you, that seems to have fixed it. The reboot did seem to be required afterwards.

It may be worth adding a little bit to the text for that option to say something like "Disable this if uninstalling." or similar; I would have caught that when I went through the app to see if there was anything special I needed to do!
