### ISSUE TITLE
need custom color map

### ISSUE THREAD

**Issue by DjinnDjab** [Mahmud0808/ColorBlendr#88]
is there some kind of method to the madness of defining custom colors and what aspect of the UI they change? i feel like i could make some cool themes or something but its wayyyyy too much trial and error to get it to look the way i want cause its impossible to know what does what and its just too much without some kind of label or key or something

**Comment by Mahmud0808** [comment]
There is no mapping or guide for that unfortunately. You will have to figure it out by trial and error.
