### ISSUE TITLE
Colors aren't switching

### ISSUE THREAD

**Issue by Turhvjbufv** [Mahmud0808/ColorBlendr#9]
So my wallpaper changes every 5 minutes and when I turn the screen off, color blender seems to be having problem detecting the wallpaper change, since several wallpapers(that all have different colors) have been switched around, and only after I open color blend, and turned off(and on) screen it detects the new color(force stop and then opening color blender also works)

**Comment by Mahmud0808** [comment]
System sends broadcast when wallpaper is changed, ColorBlendr updates color when it receives the broadcast. So make sure ColorBlendr isn't getting killed when screen is off. Doesn't look like an issue of ColorBlendr.

**Comment by Mahmud0808** [comment]
Actually you were right. ColorBlendr wasn't receiving any broadcast when app was removed from recents.
