### ISSUE TITLE
Color extraction from Muzei

### ISSUE THREAD

**Issue by hanubeki** [Mahmud0808/ColorBlendr#94]
Muzei, a live wallpaper app provides an api to get current wallpaper as bitmap.
Currently as of ColorBlendr 1.5, it extracts colors from the Muzei app icon but it would be nice if ColorBlendr can extract colors from Muzei's current wallpaper image.

https://api.muzei.co/reference/index.html

**Comment by Mahmud0808** [comment]
Sorry but it's a personal request. I don't want to add all the live wallpaper APIs available out there. You are free to fork and add it if you really need.

**Comment by hanubeki** [comment]
I'm trying to do that 👍
(However after some experiments, I don't feel Muzei API is actually needed as WallpaperManager.getWallpaperColors works well)
