### ISSUE TITLE
اقتراح تغيير نمط الايقونات

### ISSUE THREAD

**Issue by mohamedzerougdz** [Mahmud0808/ColorBlendr#98]
شكرا على مجهودك الجبار، حبذا لو كان يدعم تغيير الايقونات الى نمط ماتريال يو لكان افضل تطبيق على الاطلاق

**Comment by hanubeki** [comment]
I think it will need icon packs and/or launchers that supports themed icons.

**Comment by Mahmud0808** [comment]
That's a launcher feature. ColorBlendr can already change themed icon colors. If you are asking for themed icons (assuming you don't have it), this app can't and won't be able to do that.
